sudo: required

language: python

python:
  - "2.7"

before_install:
  - /bin/bash -c "cd /Nomad; cp shared/secrets.example.py shared/secrets.py; cp shared/jobmine.example.py shared/jobmine.py; cp shared/ratemycoopjob.example.py shared/ratemycoopjob.py;"

install:
  - pip install -r requirements.txt

script:
  - sudo python -m nltk.downloader -d /usr/local/share/nltk_data conll2000 conll2002 maxent_ne_chunker punkt averaged_perceptron_tagger
  - python -m unittest discover --pattern=*test.py -v
