sudo: required

language: python

python:
  - "2.7"

services:
  - mongodb
  - redis-server

before_install:
  - /bin/bash -c "cd /Nomad; cp shared/secrets.example.py shared/secrets.py; cp shared/jobmine.example.py shared/jobmine.py; cp shared/ratemycoopjob.example.py shared/ratemycoopjob.py;"

install:
  - ./travis-setup.sh
  - pip install -r requirements.txt
  - sudo mv nltk_data /usr/local/share/nltk_data

script:
  - python -m unittest discover --pattern=*test.py -v