sudo: required

language: python

python:
  - "2.7"

before_install:
  - /bin/bash -c "cd /Nomad; cp shared/secrets.example.py shared/secrets.py; cp shared/jobmine.example.py shared/jobmine.py; cp shared/ratemycoopjob.example.py shared/ratemycoopjob.py;"
  - /bin/bash -c "cd /Nomad; sudo make install_nltk_data"

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover --pattern=*test.py -v
