systemLog:
   destination: file
   path: "/home/Nomad/logs/mongo/mongo.log"
   logAppend: true
storage:
   dbPath: "/home/Nomad/data/mongo"
   journal:
      enabled: true
   bindIp: 127.0.0.1
   port: 27017
setParameter:
   enableLocalhostAuthBypass: false
processManagement:
   fork: true