"""
This module is used to manage UW programs.
"""

programs = [
    'AHS-(unspecified)',
    'AHS-Hlth Studies & Gerontology',
    'AHS-Kinesiology',
    'AHS-Public Health',
    'AHS-Rec. & Leisure Studies',
    'AHS-Sport & Business',
    'ARCH-Architecture',
    'ARTS MASTERS-Economics',
    'ARTS MASTERS-Exp Digital Media',
    'ARTS MASTERS-Literary Studies',
    'ARTS MASTERS-Political Science',
    'ARTS MASTERS-Public Service',
    'ARTS MASTERS-Rhet/Comm Design',
    'ARTS-(unspecified)',
    'ARTS-Anthropology',
    'ARTS-Arts & Business',
    'ARTS-Digital Arts Comm',
    'ARTS-Economics',
    'ARTS-English Lit & Rhetoric',
    'ARTS-English Literature',
    'ARTS-Financial Management',
    'ARTS-Fine Arts',
    'ARTS-French',
    'ARTS-Global Bus & Digital Arts',
    'ARTS-Global Engagement',
    'ARTS-HR Management',
    'ARTS-History',
    'ARTS-International Trade',
    'ARTS-Legal Studies',
    'ARTS-Management Accounting',
    'ARTS-Mathematical Economics',
    'ARTS-Philosophy',
    'ARTS-Political Science',
    'ARTS-Psychology',
    'ARTS-Rhetoric & Prof Writing',
    'ARTS-Sociology',
    'ARTS-Speech Communication',
    'All Business (unspecified)',
    'All Chart Prof Acct (CPA)',
    'All Finance (unspecified)',
    'All Health Informatics',
    'All Info Tech (unspecified)',
    'ENG MASTERS-Civil',
    'ENG MASTERS-Management Science',
    'ENG-(unspecified)',
    'ENG-Biomedical',
    'ENG-Chemical',
    'ENG-Civil',
    'ENG-Computer',
    'ENG-Electrical',
    'ENG-Environmental',
    'ENG-Geological',
    'ENG-Management',
    'ENG-Mechanical',
    'ENG-Mechatronics',
    'ENG-Nanotechnology',
    'ENG-Software',
    'ENG-Systems Design',
    'ENV- (unspecified)',
    'ENV-Env & Resource Studies',
    'ENV-Environment & Business',
    'ENV-Geog & Env Management',
    'ENV-Geomatics',
    'ENV-International Development',
    'ENV-Knowledge Integration',
    'ENV-Planning',
    'MATH MASTERS-Health Info',
    'MATH- (unspecified)',
    'MATH-Actuarial Science',
    'MATH-Applied Mathematics',
    'MATH-Bioinformatics',
    'MATH-Business Administration',
    'MATH-Combinatorics & Optimizat',
    'MATH-Computational Math',
    'MATH-Computer Science',
    'MATH-Computing & Financial Mgm',
    'MATH-Fin Analysis & Risk Mgmt',
    'MATH-IT Management',
    'MATH-Mathematical Economics',
    'MATH-Mathematical Finance',
    'MATH-Mathematical Optimization',
    'MATH-Mathematical Physics',
    'MATH-Mathematical Studies',
    'MATH-Pure Mathematics',
    'MATH-Scientific Computation',
    'MATH-Statistics',
    'MATH-Statistics for Health',
    'MATH-Teaching',
    'SCI- (unspecified)',
    'SCI-Biochemistry',
    'SCI-Bioinformatics',
    'SCI-Biology',
    'SCI-Biotechnology/Economics',
    'SCI-Chemistry',
    'SCI-Earth Sciences',
    'SCI-Environmental Science',
    'SCI-Geology and Hydrogeology',
    'SCI-Optometry',
    'SCI-Pharmacy',
    'SCI-Physics',
    'SCI-Psychology',
    'SCI-Science/Business',
]